### PR TITLE
Trio remote control

### PR DESCRIPTION
**Pull request by bjorkert**
Remote Control for Trio 1.0

In LoopFollow, a new option is introduced in Remote Settings: Trio Remote Control.
This new Remote Control features Apple Push Notifications in order to deliver remote commands to Trio. 

You will need to enter a shared secret (Available in Trio), your APNS Key ID and APNS Key.

There are also guardrails available for bolus, carbs, protein and fat.

In the remote tab, you can use Meal for sending remote carbs/fat/protein. Bolus for remote bolusing. Temp Target for setting a temp target (or set up preset temp targets that are locally in your LoopFollow) or use Overrides (defined in Trio).

When sending a command, you will get a message indicating if the sending is a success or not. This does not mean that Trio has acted on the command. Depending on many factors, it can take from seconds (if the app is open, good network coverage) or many minutes (if the phone is used for playing games that takes lots of resources). Trio will accept a message that is up to 10 minutes old, after that it will be rejected. Trio will also reject a bolus or carbs command if there was other boluses or carbs entries created after the command was created, in order to avoid overdosing. If Trio rejects a command, it will be logged as a Note-entry, visible in LoopFollow and Nightscout.

### CODE REVIEW

**Comment by marionbarker** [comment]
## Status

Success

## Comments

This comment only covers the Trio 0.2.2 portions of this interface between LoopFollow and Trio.

LoopFollow interacts with TempTargets for Trio 0.2.2 using the new Remote icon on the main screen toolbar.

No other remote features using LoopFollow as entry mechanism are available using this branch with Trio 0.2.2.

## Requests

I think the LoopFollow, Settings, Remote Settings screen needs some information included on screen.

Remote Type shows as None, Nightscout or Trio Remote Control

Possible words to add:

* Nightscout is the only option available for released version of Trio
* Trio Remote Control requires a special version of Trio, which is under development in a private repository until sufficient testing is completed.

## Test Summary Results

Changes update quickly to plots for LoopFollow (LF), Nightscout (NS) and Trio phone except for the LF Info Table which is fed from the OpenAPS pill. The OpenAPS pill updates with the next cycle, and then the LF Info Table updates. I believe this is expected behavior but needs to be explained in the LoopFollow remote documentation.

### Remote Settings Choices

* Remote Settings = None and tap on Remote in toolbar, told to go to settings
* Remote Settings = Nightscout (see test results below)
* Remote Settings = Trio Remote Control (shows a bunch of fields to fill out that require the private testing version)
    * The 4 icons that work with the private version of Trio show up
    * If a user attempts to use one, they are told there are missing fields.

### Tests with Nightscout Option

All these test were successful and behaved as expected:

1. set a TT on Trio phone and see it appear on NS and LF plots; update in OpenAPS pill and LF Info Table at next cycle
1. cancel that same TT on LoopFollow phone and see it cancel on NS and Trio plots; update in OpenAPS pill and LF Info Table at next cycle
1. set a TT on LF phone and see it appear on NS and Trio plots; update in OpenAPS pill and LF Info Table at next cycle
1. cancel the TT on Trio phone and see it cancel on NS and LF plots; update in OpenAPS pill and LF Info Table at next cycle
1. create two named TT in LF and then choose one; see it appear on NS and Trio plots; update in OpenAPS pill and LF Info Table at next cycle
1. enable named TT in LF, wait for it to appear in NS, Trio and OpenAPS pill; and then cancel the TT using NS Careportal with entered by set to remote - behaves as expected

**Review by marionbarker — APPROVED** [review]
See my comments. IMO, this can be merged to dev (for Trio 0.2.2 use) without modification although I think the added information on the Remote Settings page would be helpful.

**Comment by bjorkert** [comment]
@marionbarker, just pushed "Instructions for Remote Type options".
I think it would be good to merge to dev now, I have some other non-trio features I would like to add.
Simulator 2024-11-10 13 01 36

**Comment by marionbarker** [comment]
## Status
Successful test for Trio 0.2.2 on "looper's" phone

## Configuration
* looper's phone is an iPhone SE running 18.1 with an rPi pump and NS as a CGM
   * Trio 0.2.2 (`main` branch, commit `d97ee5e8`)
* LoopFollow phone is an iPhone 7+ running 15.8.3
   * `trio_remote_control` branch, commit 42f8558 

## Tests for Trio 0.2.0

### Message on LoopFollow Settings Remote Control
* added message is good when selecting the 3 options

### From LoopFollow send temp target commands to Trio phone
* success: message that it was sent to NS is seen but nothing happens on Trio phone when remote control is disabled on the trio phone
* success: temporary target (value and duration), seen on LF, NS and Trio main screen (upper bar)
   * cancel it early from LoopFollow phone and it is cancelled from NS, Trio and LF phones 
   * go to Temp Target screen on Trio phone (it doesn't show up except on main screen), tap cancel and it is cancelled on Trio phone and NS; after refresh, it goes away on LoopFollow phone
* success: save as preset and send the named preset (shows up with target value, top of Trio main display); let it run planned duration
   * Named presets names created on LoopFollow phone, visible only on LoopFollow side 

### From Trio phone, apply temp target and override
* create a named preset and apply, it appears in NS and on LoopFollow phone
   *  Named presets names created on Trio phone, visible only on Trio side 
   * cancel temp target on LoopFollow phone, it is canceled in NS and on Trio phone

**Comment by marionbarker** [comment]
## Status
The Browser Build for Trio does not seem to work.

## Test build source for Trio

Determine if the remote control works from the same LoopFollow phone using different build methods.

1. The previous [comment](https://github.com/loopandlearn/LoopFollow/pull/328#issuecomment-2479633843) used a build for the Trio phone created with Xcode 16.1 using manually signed targets.
   * NS profile items: `"teamID":"myvalue", "isAPNSProduction":false, "deviceToken":"427a5b etc"`
   * all remote commands work
1. Install a GitHub Browser Build version for Trio phone
   * NS profile items: `"teamID":"myvalue", "isAPNSProduction": true, "deviceToken":"b2981b etc"`
   * remote control does not work from LoopFollow phone
   * start an override from Trio phone, observe it on NS and LF - cancel the override from LF phone, command is accepted but it does not cancel anything
1. Fresh build for the Trio phone created with Xcode 16.1 using automatically signed targets.
   * NS profile items: `"teamID":"myvalue", "isAPNSProduction":false, "deviceToken":"427a5b etc"`
   * all remote commands work

**Comment by marionbarker** [comment]
## Status
My credential tests were successful. Warning - another user reports he is still having trouble with his credentials.

## Update since last test

The Browser Build method for Trio-dev (private repo) was updated. It now has the correct value for `isAPNSProduction` and for `teamID`.

The Mac-Xcode build method for Trio-dev (private repo) was updated. It now has correct value for `teamID` regardless of the signing method.

Build using this new version and see what it takes to update or remove valid credentials from the LoopFollow-Trio phone pair.

## Configuration

* iPhone 8: LoopFollow: `cb55221`
* iPhone SE: Trio-dev:`fbdc3a2ad` (browser build version)
* Nightscout Site: created using Google Cloud method, version 15.0.2

## Testing

The initial state was that all remotes were all working.

### Credential Test 1

Install an old version of the browser build that should fail because`isAPNSProduction` and`teamID` are incorrect.
* Intially remotes continue to work, so clearly there is some memory that allows this to keep working
   * In previous tests, when I tested the next day, the status (working or not working) changed to match the state of the credentials (valid or invalid)

1. Select Nightscout in LoopFollow, Settings, Remote Settings
   * Test sending a TempTarget (all that is available with Nightscout selection) - this works
2. Select Trio Remote Control in LoopFollow, Settings, Remote Settings
   * Test sending a Override - LoopFollow reports a Credential error and doesn't try to send remote

### Credential Test 2

Build with Xcode (same `fbdc3a2ad` commit) using manual signing and removing the override config file.

1. Attempt to send a remote command and get the same Credential error on LoopFollow phone (even though it should now be correct.)
2. Select None in LoopFollow, Settings, Remote Settings
   * Get the nice message: Please select a Remote Type in Settings.
3. Select Trio Remote Control in LoopFollow, Settings, Remote Settings
   * Test sending a Override from LoopFollow - it is accepted and seen in Nightscout, Trio and LoopFollow phones
   * Repeat a hand full of other remotes, they all work as expected

**Comment by marionbarker** [comment]
## Status Summary

These are items that I noted need to be fixed before this can be merged to `dev` branch of LoopFollow.

### Credential Issues
* At this point in time, there is still one tester who is having trouble with credentials.

### LoopFollow Issues
* The behavior when carbs exceed maxCarb is not the same as when the bolus exceeds maxBolus
   * Tap `Send Meal` directly, the carb count is decreased without warning and user is asked to Confirm
   * Tap keyboard icon, the expected Validation Error is displayed
* The timestamp for uploading carb entries to Nightscout (especially when selecting carbs in the future) needs to include at least the current seconds and not just hh:mm:00. 
   * Otherwise Nightscout does not recognize them as multiple carb entries, instead it overwrites with the latest carb entry entered at that hh:mm:00 time. 
   * Trio does record them as separate entries.
   * See this LoopCaregiver commit [Use Random carb entry seconds to avoid NS issues reflecting carbs](https://github.com/LoopKit/LoopCaregiver/commit/ce5bde8cabfd53a690fbc811dd25ef7af3148f96)
   * See this Issue: [cgm-remote-monitor Issue 8185: Carb treatments disappearing](https://github.com/nightscout/cgm-remote-monitor/issues/8185)
* The `Meal with Bolus` option for Meal entry sends a bolus command without requesting authorization, this should be updated to require authorization.
* The `Meal with Bolus` option for Meal should have an extra note, e.g., "Carbs are entered in the future, while bolus is enacted now."

**Pull request merged**
