### PR TITLE
Update to Xcode 15 and iOS 17 SDK for App Store compliance

### PR DESCRIPTION
**Pull request by bjorkert**
Updated the build system to use Xcode 15 and iOS 17 SDK to meet the latest App Store requirements.

### CODE REVIEW

**Comment by marionbarker** [comment]
I believe this is insufficient. Asking @dnzxy to review. 

See https://github.com/LoopKit/LoopWorkspace/pull/120

**Review by dnzxy — APPROVED** [review]
This should be okay. I‘d suggest also bumping all other actions (validate, identifiers, certificates) to macOS 13 runners.  Unfortunately, `macos-14` are still in beta state for GH.

**Comment by bjorkert** [comment]
Thanks @dnzxy, good point! I have pushed that change now!

**Comment by bjorkert** [comment]
Fixes #258

**Pull request merged**
