### PR TITLE
iAPS support for LoopFollow

### PR DESCRIPTION
**Pull request by bjorkert**
- Auto detection of iAPS devicestatus vs Loop
- A new info table category "Autosens" was added.
- infoTable.rowHeight changed from 24 to 21.
- Carbs today is now based on created_at instead of timestamp to fit iAPS
- Ensured that infoVisible values have the correct default settings and length. This fixes a bug that made LF crash for some users at rebuilding.
- The title of a switch for downloading data was updated from "Download Loop/FreeAPS Data" to "Download Loop/iAPS Data".

Many changes are copied/inspired from/by this fork: https://github.com/aug0211/aug0211-LoopFollowFAX/tree/fax

### CODE REVIEW

**Comment by bjorkert** [comment]
I've identified a regression in the iAPS branch: the Loop overrides are no longer displayed as a banner/stripe.

**Comment by bjorkert** [comment]
Closes https://github.com/loopandlearn/LoopFollow/issues/134

**Comment by flyingpie101** [comment]
Not sure if this is the right place to comment.
1.  The eventual BG display directly under the current BG time since value, is hardcodes to mg/dl and doesnt follow the mmol setting.
image

2. Auggie's version also had a min/max in the information screen on the right.  not as important to me personally, but others might be using it.

**Comment by bjorkert** [comment]
1) Thank you. I'll fix that!
2) Min/Max is now "Pred.", it is re-using the same label as LF used for Loop. I hope that is ok, otherwise it can be improved further on.

**Comment by flyingpie101** [comment]
> 1. Thank you. I'll fix that!
> 2. Min/Max is now "Pred.", it is re-using the same label as LF used for Loop. I hope that is ok, otherwise it can be improved further on.

Pred is fine.  I am sorry I didnt notice it.

**Comment by bjorkert** [comment]
> > 1. Thank you. I'll fix that!
> > 2. Min/Max is now "Pred.", it is re-using the same label as LF used for Loop. I hope that is ok, otherwise it can be improved further on.
> 
> Pred is fine. I am sorry I didnt notice it.

Thank you for the feedback. I've made the necessary adjustments. Could you please build the latest version and check out the fix? Really appreciate your input on this. We're getting close to merging this PR. Anything else you'd like to point out or suggest before we go ahead? Hope everything looks good on your side!

**Comment by flyingpie101** [comment]
Built and testing. So far, so good. 

I do have 1 request that I personally think would be nice.  And I 'bug' that is less important.

Request:
In the OpenAPS pill, there is occasionally a pice of info saying "Additional 13 carbs required with in 10 mins" or whatever the values need to be.   It would be great to be able to see in the informational display of top right of LF a new line saying "Carbs Needed"

Bug:
We did a Dexcom change last night, and after about 30 mins, if I launched LF, it would just crash/close.  Once readings started coming in again, it would launch fine. Not a high priority for me.  But worth mentioning.

**Comment by bjorkert** [comment]
Thanks for the feedback!

I've noted the "Carbs Needed" suggestion and the LF crash issue in my to-do list. Definitely something to look into.

Considering our earlier convo, I think it's best we merge this PR if it aligns with the FAX branch and current LF. We can handle these new points in follow-up updates. Sound good?

Appreciate your input as always!

**Comment by flyingpie101** [comment]
Works for me.

Thx

Greg

**Pull request merged**
