### PR TITLE
Temp target for Trio

### PR DESCRIPTION
**Pull request by bjorkert**
New Functionality:
	•	Temporary Targets for Trio: Users can now set and cancel temporary targets. Future versions can include override handling for Loop.

Prerequisites: Trio and a Nightscout token with careportal and careportal roles, admin is also ok. The NS Status will indicate if your token has Read or Read+Write auth.

Refactoring:
	•	Alarm Tab Relocation: The Alarm tab has been moved to the settings menu and replaced by the new Remove view.
	•	Introducing HKQuantity and HKUnit.
	•	Observable User Defaults and Variables: Introduced observable user defaults and variables for better state management.
	•	iOS Target Update: Updated the iOS target from 13.4 to 15.6. This change should have minimal impact, as all devices running 13.4 can upgrade to 15.6.
	•	Build Details in Detached Mode: Capture build details now supports detached mode, allowing for builds outside of a branch or tag.
	
image
image
image
CleanShot 2024-07-31 at 10 15 46@2x

### CODE REVIEW

**Comment by bjorkert** [comment]
Presets feature added:
image

**Comment by marionbarker** [comment]
## Code Review:
* Fairly superficial
* Noted clean up and refactoring
* Glanced over new remote code

## Test
Planned tests - report in successive comments:
1. display tests
1. alarm tests
1. remote tests for Trio

### Display tests
* test with several Loop URL - looks nominal
* test with several Trio ULR - looks nominal
* test "remote" for each (without authorization) and get appropriate information screen, see graphic below (note did one Trio URL with read token and one Trio URL that is unprotected. Both gave the same response for remote)

lf-pr-321-invalid-remote

**Comment by marionbarker** [comment]
### Remote Tests for Trio
* configuration - test phone running Trio dev, commit 4f08c0f
* upload to test nightscout site
* connect that site to Loop Follow of this branch
* add rPi DASH simulator to test phone (so it will run in the background)

Look at LoopFollow app.
* connect to the same NS site but this time with a token with careportal, read roles
* do NOT enable Trio remote control
* LF says it send Temp Target to Nightscout, but of course did not do anything.
* enable fetch treatments and remote control on Trio app
* Temp Target is set to 110 (noticed this later in OpenAPS pill)
* Remove Temp Target, target restores to 99

Repeat more cleanly
* send TT of 110 from LF
* shows up on LF as set, but does not seem to be on Trio app or Trio pill
* wait about 6 minutes until pill updates - see Target now at 110
* and the information on the Trio phone shows Target: 110
* doesn't show up anywhere other than the pill for Trio phone and NS site.
* I think there's an indication on the Trio phone on the plot
* wait 20 minutes for TT to expire naturally (set for 20 min duration)
* The NS treatment show temp target with 20 min duration but no glucose level is shown

**Review by marionbarker — APPROVED** [review]
OK to merge to dev if @bjorkert is ready or leave here for more updates
Not a Trio user or remote user.
Limited amount of testing for that part.

**Pull request merged**
