### PR TITLE
Use iAPS colours for COB, IOB, UAM and ZT, refactor colouring

### PR DESCRIPTION
**Pull request by bjornoleh**
Use iAPS colours for COB, IOB, UAM and ZT, refactor colouring by copying iAPS colour assets

### CODE REVIEW

**Comment by bjornoleh** [comment]
This is a suggested fix for https://github.com/loopandlearn/LoopFollow/issues/221

**Comment by bjornoleh** [comment]
Adapted to refactor

**Comment by marionbarker** [comment]
Holding on this because there may be a color update to iAPS soon.

**Comment by bjornoleh** [comment]
> Holding on this because there may be a color update to iAPS soon.

I added the corrected colour for basal in dark mode from a pending PR by @dnzxy to iAPS now. This colour is not used  for the prediction lines in this current PR though, but nice to have the full colorset up to date in case these will be used later. The change is just a fix for all the colour components being set to 1,00, which gives the colour gray. No need for this to be merged into iAPS.

There are not any further pending changes to these colours. If anything should change later, we can make a separate PR for that.

**Comment by marionbarker** [comment]
tested that it builds. Merging to dev for staging there. Allow iAPS folks time to evaluate all these changes in one place.

**Pull request merged**
